name = "unisa-tracker"
main = "src/worker.js"
compatibility_date = "2025-01-01"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[kv_namespaces]]
binding = "TRACKER"
id = "94dcf697d00d43bab6f24986dad8c063"

[observability]
[observability.logs]
enabled = true
invocation_logs = true
[observability.traces]
enabled = true
